# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9d38b11fd866dc1ddd47cda4e6c19b9543405831581ea9c3070e59120b5297afd1f9c450a88b8264b4a294de44a7ac473dc0844352d651928c0698f59157e6

test:
  secret_key_base: 169c7d1f892740ae9a62b9dfe9826de101b8370520de0fdcc0aa657b42e9b15a360d873321c94a6907e3f4f2e03ba7fb57ea90a78991a6564c28727fb0a77a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
